# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: HNO3Miracle <xiangao.or@isrc.iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%define _name           otel
%define go_import_path  go.opentelemetry.io/otel

Name:           go-opentelemetry-otel
Version:        1.43.0
Release:        %autorelease
Summary:        Go module dependency for Prometheus
License:        Apache-2.0
URL:            https://github.com/open-telemetry/opentelemetry-go
#!RemoteAsset:  sha256:f8ce59f6705b718114124b234a5761a9e9141261faa9b31d4a2a86b14e988e52
Source0:        https://github.com/open-telemetry/opentelemetry-go/archive/v%{version}.tar.gz#/%{_name}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    golangmodules

# go.opentelemetry.io/otel/internal/global imports go.opentelemetry.io/auto/sdk,
# while auto/sdk imports otel APIs. Limit bootstrap %check to leaf API packages
# that do not require auto/sdk so the BuildRequires cycle can be resolved.
%define go_test_include %{shrink:
    %{go_import_path}/attribute
    %{go_import_path}/baggage
    %{go_import_path}/codes
}

BuildRequires:  go
BuildRequires:  go(github.com/cespare/xxhash/v2)
BuildRequires:  go(github.com/davecgh/go-spew)
BuildRequires:  go(github.com/go-logr/logr)
BuildRequires:  go(github.com/go-logr/stdr)
BuildRequires:  go(github.com/google/go-cmp)
BuildRequires:  go(github.com/pmezard/go-difflib)
BuildRequires:  go(github.com/stretchr/testify)
BuildRequires:  go(gopkg.in/yaml.v3)
BuildRequires:  go-rpm-macros

Provides:       go(go.opentelemetry.io/otel) = %{version}
Requires:       go(github.com/cespare/xxhash/v2)
Requires:       go(github.com/go-logr/logr)
Requires:       go(github.com/go-logr/stdr)
# Do not add Requires: go(go.opentelemetry.io/auto/sdk) here: auto/sdk
# imports otel APIs, and OBS expands runtime Requires while resolving
# BuildRequires, which would make the bootstrap cycle unbuildable.

%description
Go module dependency for Prometheus. Generated by go2spec.

%files
%doc README.md
%doc CHANGELOG.md
%doc CONTRIBUTING.md
%license LICENSE
%{go_sys_gopath}/%{go_import_path}
# Nested Go modules are packaged separately; do not let the root module own
# their source directories, otherwise BuildRequires that install both packages
# will hit RPM file conflicts.
%exclude %{go_sys_gopath}/%{go_import_path}/bridge/opencensus
%exclude %{go_sys_gopath}/%{go_import_path}/bridge/opentracing
%exclude %{go_sys_gopath}/%{go_import_path}/exporters/otlp/otlplog/otlploggrpc
%exclude %{go_sys_gopath}/%{go_import_path}/exporters/otlp/otlplog/otlploghttp
%exclude %{go_sys_gopath}/%{go_import_path}/exporters/otlp/otlpmetric/otlpmetricgrpc
%exclude %{go_sys_gopath}/%{go_import_path}/exporters/otlp/otlpmetric/otlpmetrichttp
%exclude %{go_sys_gopath}/%{go_import_path}/exporters/otlp/otlptrace
%exclude %{go_sys_gopath}/%{go_import_path}/exporters/otlp/otlptrace/otlptracegrpc
%exclude %{go_sys_gopath}/%{go_import_path}/exporters/otlp/otlptrace/otlptracehttp
%exclude %{go_sys_gopath}/%{go_import_path}/exporters/prometheus
%exclude %{go_sys_gopath}/%{go_import_path}/exporters/stdout/stdoutlog
%exclude %{go_sys_gopath}/%{go_import_path}/exporters/stdout/stdoutmetric
%exclude %{go_sys_gopath}/%{go_import_path}/exporters/stdout/stdouttrace
%exclude %{go_sys_gopath}/%{go_import_path}/exporters/zipkin
%exclude %{go_sys_gopath}/%{go_import_path}/internal/tools
%exclude %{go_sys_gopath}/%{go_import_path}/log
%exclude %{go_sys_gopath}/%{go_import_path}/log/logtest
%exclude %{go_sys_gopath}/%{go_import_path}/metric
%exclude %{go_sys_gopath}/%{go_import_path}/schema
%exclude %{go_sys_gopath}/%{go_import_path}/sdk
%exclude %{go_sys_gopath}/%{go_import_path}/sdk/log
%exclude %{go_sys_gopath}/%{go_import_path}/sdk/log/logtest
%exclude %{go_sys_gopath}/%{go_import_path}/sdk/metric
%exclude %{go_sys_gopath}/%{go_import_path}/trace
%exclude %{go_sys_gopath}/%{go_import_path}/trace/internal/telemetry/test

%changelog
%autochangelog
